### ISSUE TITLE
Error upon start

### ISSUE THREAD

**Issue by moppman** [Selur/Mis2x265#1]
I downloaded the Win build from your page.
However, the 64 bit version throws this error:

![clipboard01](https://cloud.githubusercontent.com/assets/10085380/8995105/aee6711c-370f-11e5-95cf-16a8dd5f88e2.png)

I'm on a fresh Win 10 64bit build.
The qwindows.dll is in the "programs" folder is it should be, maybe it has something to do with a missing libEGL.dll?

**Comment by Selur** [comment]
Re-Uploaded the download, but this time I didn't pack the binaries with UPX, which seems to cause problems on Win10.

Cu Selur

**Comment by moppman** [comment]
Yup, fixed :)
